---
- name: Update servers and log
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Write a log message on the server
      copy:
        content: "Ansible est passé sur ce serveur le {{ ansible_date_time.iso8601 }}"
        dest: /var/log/ansible_update.log
        owner: root
        group: root
        mode: '0644'
