---
- hosts: all
  become: true
  tasks:

    - name: Update APT cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update APK packages (Alpine)
      apk:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == "Alpine"
